#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# a
list_teams:
  path: /equipos
  controller: App\Controller\EquipoController::listOfTeams

# b
list_a_team:
  path: /equipos/{teamName}
  controller: App\Controller\EquipoController::infoOfATeam

# c
players_by_teams:
  path: /equipo/jugadores
  controller: App\Controller\JugadoresController::playersByTeams

# d
players_by_team_name:
  path: /equipo/jugadores/{teamName}
  controller: App\Controller\JugadoresController::playersByTeamName

# e
list_players:
  path: /jugadores
  controller: App\Controller\JugadoresController::listOfPlayers

# f
list_a_player:
  # 'blank space' is typed as '%20'
  path: /jugadores/{playerName}
  controller: App\Controller\JugadoresController::infoOfAPlayer

# g
height_weight_position_of_a_player:
  path: /jugador/fisico/{playerName}
  controller: App\Controller\JugadoresController::heightWeightPositionOfAPlayer

# h
stats_of_a_player:
  path: /estadisticas/jugador/{playerName}
  controller: App\Controller\EstadisticasController::statsOfAPlayer

# i
average_stats_of_a_player:
  path: /estadisticas/jugador/{playerName}/avg
  controller: App\Controller\EstadisticasController::averageStatsOfAPlayer

# j
home_results_of_a_team:
  path: /partidos/resultados/local/{homeTeamName}
  controller: App\Controller\PartidosController::homeResultsOfATeam

# k
away_results_of_a_team:
  path: /partidos/resultados/visitante/{teamName}
  controller: App\Controller\PartidosController::awayResultsOfATeam

# l
average_points_recived_home_of_a_team:
  path: /partidos/resultados/media/local/{teamName}
  controller: App\Controller\PartidosController::averageHomePointReceivedOfATeam

# m
average_points_recived_away_of_a_team:
  path: /partidos/resultados/media/visitante/{teamName}
  controller: App\Controller\PartidosController::averageAwayPointReceivedOfATeam