#index:
#    path: /
#    controller: App\Controller\DefaultController::index

list_teams:
  path: /equipos
  controller: App\Controller\EquipoController::listOfTeams

list_a_team:
  path: /equipos/{teamName}
  controller: App\Controller\EquipoController::infoOfATeam